USE wildcircus;

INSERT INTO representation (title,description,category)
VALUES 
('Amazing Magic with Tommy Wind', 
'Direct from national television appearances like Access Hollywood, one of the most talented magicians in Las Vegas is wowing audiences with his incredible illusions. Amazing Magic is your chance to see Vegas headliner Tommy Wind in action as he charms the audience with breathtaking tricks, original humor, and illusions with his assistant on stage. ',
'MAGIC'),
('Criss Angel MINDFREAK',
'Rated “The #1 Magic Show of All Time,”  The new immersive evolution of MINDFREAK is a wildly entertaining show that seamlessly weaves ground-breaking mysterious illusions with pyrotechnics, gripping LED effects, new video content and cutting-edge technology never before seen on a live stage.',
'HIGHLIGHTS'),
('Thomas John – Celebrity Psychic Medium',
'Get ready for a powerfully entertaining evening that will inspire you and may even change your life. As a renowned psychic medium and clairvoyant for the world’s biggest celebrities, Thomas John has been cultivating his special gifts since he was a child. ',
'HIGHLIGHTS'),
('Penn & Teller',
'For those looking for some outrageous comedy in their magic show will get that and so much more with Penn & Teller at the Rio Las Vegas. During their 10-year run at the Penn & Teller Theater, this duo has become one of the must-see Las Vegas shows. Penn, the much bigger and verbose of the two, does all the talking. ',
'COMEDY'),
('The Mac King Comedy Magic Show', 'His passion for entertainment and all things magic have left lasting impressions with fans, audience members, fellow comedians and magicians alike, making Mac King a leading performer in Entertainment Capital of the World. BestofVegas.com has your tickets to The Mac King Comedy Magic Show, a unique, family-friendly comedy and magic performance.',
'MAGIC'),
('Cirque du soleil',
'Cirque du Soleil spins an epic and elaborate journey unlike any other on the stage of the MGM Grand. This is an epic tale of an empire rise and the tale of a pair of twins on a journey to find and fulfill their destinies. The troupe of Cirque du Soleil delivers a stunning acrobatic performance.',
'ACROBAT'),
('Cirque du soleil',
'A return to our origins, KOOZA combines acrobatic performance and the art of clowning, while exploring fear, identity, recognition and power. The Innocents journey brings him into contact with comic characters from an electrifying world full of surprises, thrills, audacity and total involvement.',
'ACROBAT'),
('Zumanity',
'Zumanity is a seductive twist on reality, making the provocative playful and the forbidden electrifying! Leave inhibitions at the door, let loose and marvel in a sexy thrill ride full of sensational acrobatics and naughty fun. Part burlesque and part cabaret, Zumanity is one full night you will never forget! ',
'DANSE'),
('BAZAAR',
'Click-click-click... One-two-three… Wheels turn again. Creative gears get moving. Superhuman roller-skaters, and circular acro-bike performer sparks a rhythmic feeling of rotation where everything connects.',
'CLOWN');


INSERT INTO artist (lastname,firstname,description,avatar)
VALUES 
('GROCK','Jack','the most funny guy in the wolrd','http://www.auvergne-jouets.com/466-tm_large_default/mascotte-clown.jpg'),
('OUDINI', 'Hagrid', 'Neutris infidos ut ad eum a fit Coluntur amicorum enim quem simulatione a ceciderunt intellegitur eum enim referre quam forte amicorum quam inopes fidos exsulantem quem se eum metuat Quod a enim gratiam metui cum eum cum tempus tamen exsulantem.', 'https://media.gettyimages.com/vectors/magicians-hat-with-mac-if-coming-out-vector-id134454783?s=2048x2048'),
('GEORGES','Mickeal', 'Neutris infidos ut ad eum a fit Coluntur amicorum enim quem simulatione a ceciderunt intellegitur eum enim referre quam forte amicorum quam inopes fidos exsulantem quem se eum metuat Quod a enim gratiam metui cum eum cum tempus tamen exsulantem.','https://www.google.com/url?sa=i&source=images&cd=&ved=2ahUKEwic5MDG_arnAhXwyYUKHRNpDiAQjRx6BAgBEAQ&url=https%3A%2F%2Fwww.imprim-deco.fr%2Fstickers-enfant%2F3339-sticker-mural-danseur-hip-hop.html&psig=AOvVaw3cU9FdZj49-NoFHeDrd8bw&ust=1580461908179414'),
('MONTERAI', 'Gabriela', 'Neutris infidos ut ad eum a fit Coluntur amicorum enim quem simulatione a ceciderunt intellegitur eum enim referre quam forte amicorum quam inopes fidos exsulantem quem se eum metuat Quod a enim gratiam metui cum eum cum tempus tamen exsulantem.','https://www.google.com/url?sa=i&source=images&cd=&ved=2ahUKEwic5MDG_arnAhXwyYUKHRNpDiAQjRx6BAgBEAQ&url=https%3A%2F%2Fwww.imprim-deco.fr%2Fstickers-enfant%2F3339-sticker-mural-danseur-hip-hop.html&psig=AOvVaw3cU9FdZj49-NoFHeDrd8bw&ust=1580461908179414'),
('GROBESKI', 'Ulrich', 'Neutris infidos ut ad eum a fit Coluntur amicorum enim quem simulatione a ceciderunt intellegitur eum enim referre quam forte amicorum quam inopes fidos exsulantem quem se eum metuat Quod a enim gratiam metui cum eum cum tempus tamen exsulantem.','https://www.google.com/url?sa=i&source=images&cd=&ved=2ahUKEwjnncTn-6rnAhU54eAKHUzjDskQjRx6BAgBEAQ&url=http%3A%2F%2Fwww.auvergne-jouets.com%2Fpersonnages%2F143-mascotte-clown.html&psig=AOvVaw3O5iGdFUx-4u5g4QH-rPzm&ust=1580461431625146'),
('GROBESKI', 'Ariana', 'Neutris infidos ut ad eum a fit Coluntur amicorum enim quem simulatione a ceciderunt intellegitur eum enim referre quam forte amicorum quam inopes fidos exsulantem quem se eum metuat Quod a enim gratiam metui cum eum cum tempus tamen exsulantem.','https://www.google.com/url?sa=i&source=images&cd=&ved=2ahUKEwjnncTn-6rnAhU54eAKHUzjDskQjRx6BAgBEAQ&url=http%3A%2F%2Fwww.auvergne-jouets.com%2Fpersonnages%2F143-mascotte-clown.html&psig=AOvVaw3O5iGdFUx-4u5g4QH-rPzm&ust=1580461431625146'),
('GROCK','Jack','the most funny guy in the wolrd','http://www.auvergne-jouets.com/466-tm_large_default/mascotte-clown.jpg'),
('OUDINI', 'Hagrid', 'Neutris infidos ut ad eum a fit Coluntur amicorum enim quem simulatione a ceciderunt intellegitur eum enim referre quam forte amicorum quam inopes fidos exsulantem quem se eum metuat Quod a enim gratiam metui cum eum cum tempus tamen exsulantem.', 'https://media.gettyimages.com/vectors/magicians-hat-with-mac-if-coming-out-vector-id134454783?s=2048x2048'),
('GEORGES','Mickeal', 'Neutris infidos ut ad eum a fit Coluntur amicorum enim quem simulatione a ceciderunt intellegitur eum enim referre quam forte amicorum quam inopes fidos exsulantem quem se eum metuat Quod a enim gratiam metui cum eum cum tempus tamen exsulantem.','https://www.google.com/url?sa=i&source=images&cd=&ved=2ahUKEwic5MDG_arnAhXwyYUKHRNpDiAQjRx6BAgBEAQ&url=https%3A%2F%2Fwww.imprim-deco.fr%2Fstickers-enfant%2F3339-sticker-mural-danseur-hip-hop.html&psig=AOvVaw3cU9FdZj49-NoFHeDrd8bw&ust=1580461908179414'),
('MONTERAI', 'Gabriela', 'Neutris infidos ut ad eum a fit Coluntur amicorum enim quem simulatione a ceciderunt intellegitur eum enim referre quam forte amicorum quam inopes fidos exsulantem quem se eum metuat Quod a enim gratiam metui cum eum cum tempus tamen exsulantem.','https://www.google.com/url?sa=i&source=images&cd=&ved=2ahUKEwic5MDG_arnAhXwyYUKHRNpDiAQjRx6BAgBEAQ&url=https%3A%2F%2Fwww.imprim-deco.fr%2Fstickers-enfant%2F3339-sticker-mural-danseur-hip-hop.html&psig=AOvVaw3cU9FdZj49-NoFHeDrd8bw&ust=1580461908179414'),
('GROBESKI', 'Ulrich', 'Neutris infidos ut ad eum a fit Coluntur amicorum enim quem simulatione a ceciderunt intellegitur eum enim referre quam forte amicorum quam inopes fidos exsulantem quem se eum metuat Quod a enim gratiam metui cum eum cum tempus tamen exsulantem.','https://www.google.com/url?sa=i&source=images&cd=&ved=2ahUKEwjnncTn-6rnAhU54eAKHUzjDskQjRx6BAgBEAQ&url=http%3A%2F%2Fwww.auvergne-jouets.com%2Fpersonnages%2F143-mascotte-clown.html&psig=AOvVaw3O5iGdFUx-4u5g4QH-rPzm&ust=1580461431625146'),
('GROBESKI', 'Ariana', 'Neutris infidos ut ad eum a fit Coluntur amicorum enim quem simulatione a ceciderunt intellegitur eum enim referre quam forte amicorum quam inopes fidos exsulantem quem se eum metuat Quod a enim gratiam metui cum eum cum tempus tamen exsulantem.','https://www.google.com/url?sa=i&source=images&cd=&ved=2ahUKEwjnncTn-6rnAhU54eAKHUzjDskQjRx6BAgBEAQ&url=http%3A%2F%2Fwww.auvergne-jouets.com%2Fpersonnages%2F143-mascotte-clown.html&psig=AOvVaw3O5iGdFUx-4u5g4QH-rPzm&ust=1580461431625146'),
('GROCK','Jack','the most funny guy in the wolrd','http://www.auvergne-jouets.com/466-tm_large_default/mascotte-clown.jpg'),
('OUDINI', 'Hagrid', 'Neutris infidos ut ad eum a fit Coluntur amicorum enim quem simulatione a ceciderunt intellegitur eum enim referre quam forte amicorum quam inopes fidos exsulantem quem se eum metuat Quod a enim gratiam metui cum eum cum tempus tamen exsulantem.', 'https://media.gettyimages.com/vectors/magicians-hat-with-mac-if-coming-out-vector-id134454783?s=2048x2048'),
('GEORGES','Mickeal', 'Neutris infidos ut ad eum a fit Coluntur amicorum enim quem simulatione a ceciderunt intellegitur eum enim referre quam forte amicorum quam inopes fidos exsulantem quem se eum metuat Quod a enim gratiam metui cum eum cum tempus tamen exsulantem.','https://www.google.com/url?sa=i&source=images&cd=&ved=2ahUKEwic5MDG_arnAhXwyYUKHRNpDiAQjRx6BAgBEAQ&url=https%3A%2F%2Fwww.imprim-deco.fr%2Fstickers-enfant%2F3339-sticker-mural-danseur-hip-hop.html&psig=AOvVaw3cU9FdZj49-NoFHeDrd8bw&ust=1580461908179414'),
('MONTERAI', 'Gabriela', 'Neutris infidos ut ad eum a fit Coluntur amicorum enim quem simulatione a ceciderunt intellegitur eum enim referre quam forte amicorum quam inopes fidos exsulantem quem se eum metuat Quod a enim gratiam metui cum eum cum tempus tamen exsulantem.','https://www.google.com/url?sa=i&source=images&cd=&ved=2ahUKEwic5MDG_arnAhXwyYUKHRNpDiAQjRx6BAgBEAQ&url=https%3A%2F%2Fwww.imprim-deco.fr%2Fstickers-enfant%2F3339-sticker-mural-danseur-hip-hop.html&psig=AOvVaw3cU9FdZj49-NoFHeDrd8bw&ust=1580461908179414'),
('GROBESKI', 'Ulrich', 'Neutris infidos ut ad eum a fit Coluntur amicorum enim quem simulatione a ceciderunt intellegitur eum enim referre quam forte amicorum quam inopes fidos exsulantem quem se eum metuat Quod a enim gratiam metui cum eum cum tempus tamen exsulantem.','https://www.google.com/url?sa=i&source=images&cd=&ved=2ahUKEwjnncTn-6rnAhU54eAKHUzjDskQjRx6BAgBEAQ&url=http%3A%2F%2Fwww.auvergne-jouets.com%2Fpersonnages%2F143-mascotte-clown.html&psig=AOvVaw3O5iGdFUx-4u5g4QH-rPzm&ust=1580461431625146'),
('GROBESKI', 'Ariana', 'Neutris infidos ut ad eum a fit Coluntur amicorum enim quem simulatione a ceciderunt intellegitur eum enim referre quam forte amicorum quam inopes fidos exsulantem quem se eum metuat Quod a enim gratiam metui cum eum cum tempus tamen exsulantem.','https://www.google.com/url?sa=i&source=images&cd=&ved=2ahUKEwjnncTn-6rnAhU54eAKHUzjDskQjRx6BAgBEAQ&url=http%3A%2F%2Fwww.auvergne-jouets.com%2Fpersonnages%2F143-mascotte-clown.html&psig=AOvVaw3O5iGdFUx-4u5g4QH-rPzm&ust=1580461431625146');


